const data = [
  {
    no: 0,
    area: "現在の自宅（基準）",
    comment: "比較の前提",
    building: "",
    station: "中野富士見町駅",
    walk: "",
    built: "",
    reno: "",
    price: "",
    area_size: "",
    layout: "",
    floor: "",
    monthly: "",
    toKamiyacho: "約33分",
    toMeiji: "約28分",
    source: "",
    link: "",
  },
  {
    no: 1,
    area: "港区（麻布十番）",
    comment: "リノベ例として参考",
    building: "麻布狸穴ナショナルコート",
    station: "麻布十番駅",
    walk: "5分",
    built: "1976年3月",
    reno: "2025年7月",
    price: "6480万円",
    area_size: "44.21㎡",
    layout: "2DK",
    floor: "3階／RC5階建",
    monthly: "約16.5万円",
    toKamiyacho: "約20分",
    toMeiji: "約27分",
    source: "suumo",
    link: "https://suumo.jp/ms/chuko/tokyo/sc_minato/nc_78743915/",
  },
  {
    no: 2,
    area: "錦糸町",
    comment: "",
    building: "クラウンマンション",
    station: "錦糸町駅",
    walk: "7分",
    built: "1974年4月",
    reno: "2025年8月",
    price: "2880万円",
    area_size: "35.35㎡",
    layout: "1LDK",
    floor: "6階／RC8階建",
    monthly: "約9.3万円",
    toKamiyacho: "約26分",
    toMeiji: "約35分",
    source: "cowcamo",
    link: "https://cowcamo.jp/short_stories/g3I3UyQmZcI",
  },
  {
    no: 3,
    area: "宮崎台",
    comment: "温泉あり",
    building: "宮崎台南スカイマンション",
    station: "宮崎台駅",
    walk: "6分",
    built: "1981年9月",
    reno: "2022年",
    price: "2900万円",
    area_size: "66.55㎡",
    layout: "3LDK",
    floor: "4階／RC4階建",
    monthly: "約12.1万円",
    toKamiyacho: "約43分",
    toMeiji: "約36分",
    source: "cowcamo",
    link: "https://cowcamo.jp/short_stories/G286ZgiqGVY",
  },
  {
    no: 6,
    area: "板橋本町①",
    comment: "",
    building: "サンパレス本町",
    station: "板橋本町駅",
    walk: "3分",
    built: "1985年10月",
    reno: "2025年10月",
    price: "3180万円",
    area_size: "41.10㎡",
    layout: "1LDK",
    floor: "6階／SRC11階建",
    monthly: "約10.9万円",
    toKamiyacho: "約32分",
    toMeiji: "約38分",
    source: "cowcamo",
    link: "https://cowcamo.jp/short_stories/bPho9R0SgcA",
  },
  {
    no: 7,
    area: "王子",
    comment: "",
    building: "ライオンズマンション飛鳥山",
    station: "王子駅",
    walk: "4分",
    built: "1983年10月",
    reno: "2025年8月",
    price: "3280万円",
    area_size: "36.69㎡",
    layout: "1DK",
    floor: "2階／SRC10階建",
    monthly: "約11.6万円",
    toKamiyacho: "約35分",
    toMeiji: "約32分",
    source: "cowcamo",
    link: "https://cowcamo.jp/short_stories/eatB3HK3S9g",
  },
  {
    no: 8,
    area: "練馬",
    comment: "意外とあり＊修繕積立金値上中",
    building: "オリエンタルグリーンコーポラス",
    station: "練馬駅",
    walk: "6分",
    built: "1969年8月",
    reno: "2025年9月",
    price: "3280万円",
    area_size: "51.03㎡",
    layout: "2LDK",
    floor: "5階／RC8階建",
    monthly: "約11.6万円",
    toKamiyacho: "約41分",
    toMeiji: "約33分",
    source: "cowcamo",
    link: "https://cowcamo.jp/short_stories/z6Q9jbaMIdY",
  },
  {
    no: 9,
    area: "新江古田",
    comment: "練馬の横",
    building: "パレ豊玉",
    station: "新江古田駅",
    walk: "2分",
    built: "1980年11月",
    reno: "2025年8月",
    price: "3280万円",
    area_size: "47.73㎡",
    layout: "2LDK",
    floor: "3階／RC3階建",
    monthly: "約11.7万円",
    toKamiyacho: "約39分",
    toMeiji: "約33分",
    source: "cowcamo",
    link: "https://cowcamo.jp/short_stories/6AFBwD5ypSE",
  },
  {
    no: 10,
    area: "中野坂上",
    comment: "sinprisaと同じ感じ・躯体現し",
    building: "中野コーポビアネーズ",
    station: "中野坂上駅",
    walk: "2分",
    built: "1973年11月",
    reno: "2018年12月",
    price: "3280万円",
    area_size: "33.56㎡",
    layout: "1R",
    floor: "7階／SRC11階建",
    monthly: "約11.7万円",
    toKamiyacho: "約23分",
    toMeiji: "約17分",
    source: "cowcamo",
    link: "https://cowcamo.jp/%E6%9D%B1%E4%BA%AC%E9%83%BD/%E4%B8%AD%E9%87%8E%E5%8C%BA/%E7%84%A1%E9%AA%A8%E3%81%AB%E6%95%B4%E3%81%86",
  },
  {
    no: 11,
    area: "板橋本町②",
    comment: "南西角住戸・三面採光",
    building: "チサンマンション板橋",
    station: "板橋本町駅",
    walk: "3分",
    built: "1974年5月",
    reno: "2025年11月",
    price: "3299万円",
    area_size: "44.44㎡",
    layout: "2LDK",
    floor: "8階／SRC11階建",
    monthly: "約12.0万円",
    toKamiyacho: "約32分",
    toMeiji: "約38分",
    source: "cowcamo",
    link: "https://cowcamo.jp/short_stories/HxfN4gWd44o",
  },
  {
    no: 12,
    area: "板橋本町③",
    comment: "ペット可・クロス・クリーニングのみ",
    building: "ニューハイム板橋",
    station: "板橋本町駅",
    walk: "1分",
    built: "1976年4月",
    reno: "2026年2月予定",
    price: "3499万円",
    area_size: "55.42㎡",
    layout: "1LDK+S",
    floor: "9階／SRC13階建",
    monthly: "約12.5万円",
    toKamiyacho: "約32分",
    toMeiji: "約38分",
    source: "cowcamo",
    link: "https://cowcamo.jp/short_stories/8V23pFBMFLU",
  },
];
